#! /bin/bash

gen() {
  check_installed "sqlc"
  sqlc generate
}

check_installed() {
  if ! command -v "$1" &> /dev/null
  then
    echo "$1 could not be found. Please install it and try again."
    exit
  fi
}

build() {
  CGO_ENABLED=0 GOOS=linux go build -o bin/kayvault-backend cmd/main.go
  version=$(cat version)
  docker buildx build . -t ghcr.io/torfstack/kayvault-backend:"$version"
  docker push ghcr.io/torfstack/kayvault-backend:"$version"
}

deploy() {
  helm install
}

case $1 in
  gen)
    gen
    ;;
  build)
    build
    ;;
  deploy)
    deploy
    ;;
  *)
    echo "Invalid command"
    ;;
esac
