apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: config-yaml
          secret:
            secretName: synod
      containers:
        - name: synod
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              hostPort: 4000
          volumeMounts:
            - mountPath: "/config.yaml"
              subPath: "config.yaml"
              name: config-yaml
              readOnly: true
      imagePullSecrets:
        - name: regcred
  strategy:
    type: Recreate
