#!/bin/sh
set -eu

tags=$(git tag --list)
current_version=$(printf '%s\n' "$tags" | LC_ALL=C awk '
    /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/ { print }
' | LC_ALL=C sort -t. -k1.2,1n -k2,2n -k3,3n | tail -n 1)

current_version=${current_version:-v0.0.0}
base=${current_version%.*}
patch=${current_version##*.}
printf '%s.%s\n' "$base" "$((patch + 1))"
